BootStrap: library
From: yh549848/r/r:4.0.5

%post
  VER_BEDT=2.30.0 && \
  VER_SEACR=1.3 && \
  apt update && \
  apt install -y \
    curl && \
  rm -rf /var/lib/apt/lists/* && \
  cd /usr/local/bin && \
  curl -LO https://github.com/arq5x/bedtools2/releases/download/v${VER_BEDT}/bedtools.static.binary && \
  mv bedtools.static.binary bedtools && \
  chmod a+x bedtools && \
  cd /opt && \
  curl -LO https://github.com/FredHutch/SEACR/archive/refs/tags/v${VER_SEACR}.tar.gz && \
  tar xvf v${VER_SEACR}.tar.gz && \
  mv SEACR-* SEACR && \
  chmod a+x SEACR/*.sh && \
  rm *.tar.gz

%environment
  export PATH=/opt/SEACR:$PATH
